#======================================================================
# STANDALONE SENTAURUS DEVICE (SDEVICE) SIMULATION DECK
# 3-Stack Nanosheet NMOS GAAFET
#
# How to execute on any Linux TCAD system:
#   sdevice standalone_gaa_3ns_sdevice.cmd
#
# Prerequisites:
#   Requires GAA_3NS_NMOS_msh.tdr (generated by SDE)
#
# Electrical Characteristics Simulated:
#   1. Linear Transfer Curve (Id-Vg @ Vds = 0.05 V)  --> IdVg_Vd005_
#   2. Saturation Transfer Curve (Id-Vg @ Vds = 0.70 V) --> IdVg_Vd070_
#   3. Output Curves Family (Id-Vds @ Vgs = 0.0, 0.2, 0.4, 0.6, 0.7 V)
#======================================================================

File {
    Grid    = "GAA_3NS_NMOS_msh.tdr"
    Plot    = "GAA_3NS_NMOS_des.tdr"
    Current = "GAA_3NS_NMOS_des.plt"
    Output  = "GAA_3NS_NMOS_des.log"
}

Electrode {
    { Name = "source"    Voltage = 0.0 }
    { Name = "drain"     Voltage = 0.0 }
    { Name = "gate"      Voltage = 0.0   Workfunction = 4.4 }
    { Name = "substrate" Voltage = 0.0 }
}

Physics {
    # Degenerate statistics for 1e20 cm^-3 S/D
    Fermi

    # Advanced mobility models
    Mobility (
        DopingDep              # Ionized impurity scattering
        Enormal                # Lombardi surface roughness / transverse field
        HighFieldSaturation    # Canali velocity saturation in channel
    )

    # Recombination models
    Recombination (
        SRH ( DopingDep  TempDependence )
    )

    # Bandgap narrowing for heavily doped S/D
    EffectiveIntrinsicDensity ( OldSlotboom )
}

Math {
    Extrapolate
    Derivatives
    RelErrControl
    Digits          = 4
    Iterations      = 50
    NotDamped       = 20
    RhsMin          = 1e-15
    Method          = Super
    NumberOfThreads = 4
}

Plot {
    Potential  ElectricField/Vector
    eDensity   hDensity
    eCurrent/Vector  hCurrent/Vector  TotalCurrent/Vector
    eMobility  hMobility
    eVelocity/Vector  hVelocity/Vector
    eEparallel  hEparallel
    ConductionBand  ValenceBand
    eQuasiFermi  hQuasiFermi
    Doping  DonorConcentration  AcceptorConcentration
    SRHRecombination
}

Solve {

    # Step 1 — Electrostatic Equilibrium Solutions
    Coupled ( Iterations = 100 ) { Poisson }
    Coupled ( Iterations = 100 ) { Poisson  Electron  Hole }

    #==================================================================
    # CHARACTERISTIC 1: LINEAR TRANSFER CURVE (Id-Vg @ Vds = 0.05 V)
    #==================================================================
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.05 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVg_Vd005_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    #==================================================================
    # CHARACTERISTIC 2: SATURATION TRANSFER CURVE (Id-Vg @ Vds = 0.70 V)
    #==================================================================
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVg_Vd070_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    #==================================================================
    # CHARACTERISTIC 3: OUTPUT CURVES FAMILY (Id-Vds @ Vgs = 0.0 to 0.7 V)
    #==================================================================
    # Reset terminals to 0 V
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.0 } Goal { Name = "drain" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # --- Curve 1: VGS = 0.0 V ---
    NewCurrentPrefix = "IdVd_Vg000_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # Reset drain
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # --- Curve 2: VGS = 0.2 V ---
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.2 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVd_Vg020_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # Reset drain
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # --- Curve 3: VGS = 0.4 V ---
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.4 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVd_Vg040_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # Reset drain
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # --- Curve 4: VGS = 0.6 V ---
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.6 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVd_Vg060_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # Reset drain
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.0 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    # --- Curve 5: VGS = 0.7 V (Full ON) ---
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "gate" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }

    NewCurrentPrefix = "IdVd_Vg070_"
    Quasistationary (
        Iterations = 50 InitialStep = 0.01 Increment = 1.3 Decrement = 2.0 MaxStep = 0.025
        Goal { Name = "drain" Voltage = 0.70 }
    ) { Coupled ( Iterations = 50 ) { Poisson Electron Hole } }
}
